// Interface automatically generated by schemas-to-ts

export interface Adresse {
  street?: string;
  city: string;
  plz: number;
}
export interface Adresse_Plain {
  street?: string;
  city: string;
  plz: number;
}

export interface Adresse_NoRelations {
  street?: string;
  city: string;
  plz: number;
}

