// Interface automatically generated by schemas-to-ts

export enum Every {
  Day = 'day',
  Week = 'week',
  Secondweek = 'secondweek',
  Month = 'month',}

export interface Repetition {
  every: Every;
  enddate?: Date;
}
export interface Repetition_Plain {
  every: Every;
  enddate?: Date;
}

export interface Repetition_NoRelations {
  every: Every;
  enddate?: Date;
}

