// Interface automatically generated by schemas-to-ts

export interface Link {
  link?: string;
}
export interface Link_Plain {
  link?: string;
}

export interface Link_NoRelations {
  link?: string;
}

