// Interface automatically generated by schemas-to-ts

import { Adresse } from '../../../../components/address/interfaces/Adresse';
import { Linklist } from '../../../../components/linklist/interfaces/Linklist';
import { Adresse_Plain } from '../../../../components/address/interfaces/Adresse';
import { Linklist_Plain } from '../../../../components/linklist/interfaces/Linklist';
import { Adresse_NoRelations } from '../../../../components/address/interfaces/Adresse';
import { Linklist_NoRelations } from '../../../../components/linklist/interfaces/Linklist';

export interface Location {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    description?: any;
    Adresse: Adresse;
    dogsAllowed?: boolean;
    email?: string;
    linklist?: Linklist;
  };
}
export interface Location_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description?: any;
  Adresse: Adresse_Plain;
  dogsAllowed?: boolean;
  email?: string;
  linklist?: Linklist_Plain;
}

export interface Location_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description?: any;
  Adresse: Adresse_NoRelations;
  dogsAllowed?: boolean;
  email?: string;
  linklist?: Linklist_NoRelations;
}

export interface Location_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description?: any;
  Adresse: Adresse_Plain;
  dogsAllowed?: boolean;
  email?: string;
  linklist?: Linklist_Plain;
}
