// Interface automatically generated by schemas-to-ts

export enum Type {
  Kostenlos = 'Kostenlos',
  Kollekte = 'Kollekte',
  Eintrittspreis = 'Eintrittspreis',}

export interface Ticket {
  type: Type;
  ticketlink?: string;
  chf?: number;
}
export interface Ticket_Plain {
  type: Type;
  ticketlink?: string;
  chf?: number;
}

export interface Ticket_NoRelations {
  type: Type;
  ticketlink?: string;
  chf?: number;
}

