// Interface automatically generated by schemas-to-ts

import { Link } from '../../link/interfaces/Link';
import { Link_Plain } from '../../link/interfaces/Link';
import { Link_NoRelations } from '../../link/interfaces/Link';

export interface Links {
  website?: string;
  singlelink: Link[];
}
export interface Links_Plain {
  website?: string;
  singlelink: Link_Plain[];
}

export interface Links_NoRelations {
  website?: string;
  singlelink: Link_NoRelations[];
}

