// Interface automatically generated by schemas-to-ts

export interface Linklist {
  url: string;
  title: string;
}
export interface Linklist_Plain {
  url: string;
  title: string;
}

export interface Linklist_NoRelations {
  url: string;
  title: string;
}

