// Interface automatically generated by schemas-to-ts

export interface Musicstyle {
  Punk?: boolean;
  Metal?: boolean;
  Rock?: boolean;
  Ska?: boolean;
}
export interface Musicstyle_Plain {
  Punk?: boolean;
  Metal?: boolean;
  Rock?: boolean;
  Ska?: boolean;
}

export interface Musicstyle_NoRelations {
  Punk?: boolean;
  Metal?: boolean;
  Rock?: boolean;
  Ska?: boolean;
}

