// Interface automatically generated by schemas-to-ts

import { Musicstyle } from '../../../../components/musicstyle/interfaces/Musicstyle';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Linklist } from '../../../../components/linklist/interfaces/Linklist';
import { Event } from '../../../event/content-types/event/event';
import { Musicstyle_Plain } from '../../../../components/musicstyle/interfaces/Musicstyle';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Linklist_Plain } from '../../../../components/linklist/interfaces/Linklist';
import { Event_Plain } from '../../../event/content-types/event/event';
import { Musicstyle_NoRelations } from '../../../../components/musicstyle/interfaces/Musicstyle';
import { Linklist_NoRelations } from '../../../../components/linklist/interfaces/Linklist';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Band {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    bandname: string;
    country?: string;
    musicstyle?: Musicstyle;
    description?: string;
    bandphoto?: { data: Media };
    linklist: Linklist[];
    events?: { data: Event[] };
  };
}
export interface Band_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  bandname: string;
  country?: string;
  musicstyle?: Musicstyle_Plain;
  description?: string;
  bandphoto?: Media_Plain;
  linklist: Linklist_Plain[];
  events?: Event_Plain[];
}

export interface Band_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  bandname: string;
  country?: string;
  musicstyle?: Musicstyle_NoRelations;
  description?: string;
  bandphoto?: number;
  linklist: Linklist_NoRelations[];
  events?: number[];
}

export interface Band_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  bandname: string;
  country?: string;
  musicstyle?: Musicstyle_Plain;
  description?: string;
  bandphoto?: AdminPanelRelationPropertyModification<Media_Plain>;
  linklist: Linklist_Plain[];
  events?: AdminPanelRelationPropertyModification<Event_Plain>;
}
